#!/usr/bin/ruby
# Ruby front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.

projectName = "waccCompiler"

system("java -jar #{projectName}.jar #{ARGV[0]}")

exit $?.exitstatus
